export const auctions = [
  {
    emoji: "🐕",
    likes: 100,
    timer: "05 : 12 : 07 : 45",
    title: "Hamlet Contemplates...",
    blockchain: "BSC",
    author: "SalvadorDali",
    price: "4.89",
    avatar: "🎨",
    accent: "primary",
  },
  {
    emoji: "🦎",
    likes: 220,
    timer: "01 : 16 : 25 : 45",
    title: "Triumphant Awakening...",
    blockchain: "BSC",
    author: "Triste Francis",
    price: "4.89",
    avatar: "🌿",
    accent: "success",
    showBidButton: true,
  },
  {
    emoji: "🦌",
    likes: 90,
    timer: "07 : 12 : 02 : 47",
    title: "Living Vase 01 by Lanza...",
    blockchain: "BSC",
    author: "Freddie Carpenter",
    price: "4.89",
    avatar: "🎭",
    accent: "primary",
  },
  {
    emoji: "🐻",
    likes: 145,
    timer: "07 : 12 : 31 : 21",
    title: "Flame Dress By Balmain...",
    blockchain: "BSC",
    author: "Tyler Covington",
    price: "4.89",
    avatar: "🔥",
    accent: "danger",
  },
];
export   const sellers = [
    { name: "Crispin Berry", eth: "214.2 ETH", emoji: "🧑", gradient: "from-yellow-400 to-orange-400" },
    { name: "Samson Frost", eth: "170.3 ETH", emoji: "👨", gradient: "from-teal-400 to-green-500" },
    { name: "Tommy Alvarez", eth: "120.7 ETH", emoji: "👩", gradient: "from-pink-400 to-purple-500" },
    { name: "Windsor Lane", eth: "100.4 ETH", emoji: "🧔", gradient: "from-indigo-400 to-blue-500" },
    { name: "Andy Hurlbutt", eth: "82.79 ETH", emoji: "👦", gradient: "from-green-400 to-lime-400" },
    { name: "Blake Banks", eth: "68.2 ETH", emoji: "🧑‍🦱", gradient: "from-rose-400 to-red-500" },
    { name: "Monica Lucas", eth: "52.8 ETH", emoji: "👩‍🦰", gradient: "from-fuchsia-400 to-pink-500" },
    { name: "Matt Ramos", eth: "36.4 ETH", emoji: "🧓", gradient: "from-cyan-400 to-blue-400" },
    { name: "Harper Wilcher", eth: "29.2 ETH", emoji: "👨‍🦳", gradient: "from-amber-400 to-yellow-500" },
  ];

export  const picks = [
    {
      title: "The RenaXance Rising...",
      emoji: "💀",
      bg: "linear-gradient(135deg, var(--color-danger), transparent)",
      owner: "SalvadorDali",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Space Babe - Night 2/25",
      emoji: "🐡",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "SalvadorDali",
      eth: "4.89 ETH",
      heart: 100,
      badge: "Coming Soon",
    },
    {
      title: "CyberPrimal 042 LAN",
      emoji: "🐊",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "SalvadorDali",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Crypto Egg Stamp #5",
      emoji: "🌵",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "SalvadorDali",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Travel Monkey Club #45",
      emoji: "💣",
      bg: "linear-gradient(135deg, var(--color-danger), transparent)",
      owner: "Ralph Garraway",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Sir. Lion Swag #371",
      emoji: "🦁",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "Mason Woodward",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Cyber Doberman #766",
      emoji: "🦊",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "Freddie Carpenter",
      eth: "4.89 ETH",
      heart: 100,
    },
    {
      title: "Living Vase 01 by Lanz...",
      emoji: "🦒",
      bg: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      owner: "Tyler Covington",
      eth: "4.89 ETH",
      heart: 100,
    },
  ];
export const collections = [
    {
      title: "Creative Art Collection",
      owner: "Ralph Garraway",
      emoji: "🧑",
      main: "🏺",
      grid: ["🕺", "🤖"],
      gradient: "from-yellow-400 to-orange-400",
      bgMain: "linear-gradient(135deg, var(--color-primary-soft), var(--color-primary))",
      bg1: "linear-gradient(135deg, rgba(34,197,94,0.2), rgba(20,184,166,0.2))",
      bg2: "linear-gradient(135deg, rgba(31,41,55,0.8), rgba(17,24,39,0.9))",
    },
    {
      title: "Colorful Abstract",
      owner: "Mason Woodward",
      emoji: "👩",
      main: "🧸",
      grid: ["🔑", "🐳"],
      gradient: "from-pink-400 to-fuchsia-500",
      bgMain: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      bg1: "linear-gradient(135deg, rgba(79,70,229,0.2), rgba(37,99,235,0.2))",
      bg2: "linear-gradient(135deg, rgba(30,58,138,0.4), rgba(6,182,212,0.2))",
    },
    {
      title: "Modern Art Collection",
      owner: "Freddie Carpenter",
      emoji: "👨",
      main: "🤖",
      grid: ["💡", "🧪"],
      gradient: "from-teal-400 to-green-500",
      bgMain: "linear-gradient(135deg, var(--color-primary-soft), transparent)",
      bg1: "linear-gradient(135deg, rgba(20,184,166,0.2), rgba(34,197,94,0.2))",
      bg2: "linear-gradient(135deg, rgba(234,179,8,0.2), rgba(249,115,22,0.2))",
    },
  ];
  export const steps = [
    {
      title: "Set Up Your Wallet",
      desc: "Wallet that is functional for NFT purchasing. You may have a Coinbase account at the point but very few are actually set up to buy an NFT.",
      emoji: "💳",
      bg: "linear-gradient(135deg, #6366f1, #8b5cf6)",
      soft: "rgba(99,102,241,0.15)",
    },
    {
      title: "Add Your NFTs",
      desc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem.",
      emoji: "🖼️",
      bg: "linear-gradient(135deg, #f59e0b, #d97706)",
      soft: "rgba(245,158,11,0.15)",
    },
    {
      title: "List Them For Sale",
      desc: "Choose between auctions, fixed-price listings, and declining-price listings. You choose how you want to sell your NFTs.",
      emoji: "🏷️",
      bg: "linear-gradient(135deg, #ef4444, #dc2626)",
      soft: "rgba(239,68,68,0.15)",
    },
  ];