export const auctions = [
  {
    emoji: "🐕",
    likes: 100,
    timer: "05 : 12 : 07 : 45",
    title: "Hamlet Contemplates...",
    blockchain: "BSC",
    author: "SalvadorDali",
    price: "4.89",
    avatar: "🎨",
    accent: "primary",
  },
  {
    emoji: "🦎",
    likes: 220,
    timer: "01 : 16 : 25 : 45",
    title: "Triumphant Awakening...",
    blockchain: "BSC",
    author: "Triste Francis",
    price: "4.89",
    avatar: "🌿",
    accent: "success",
    showBidButton: true,
  },
  {
    emoji: "🦌",
    likes: 90,
    timer: "07 : 12 : 02 : 47",
    title: "Living Vase 01 by Lanza...",
    blockchain: "BSC",
    author: "Freddie Carpenter",
    price: "4.89",
    avatar: "🎭",
    accent: "primary",
  },
  {
    emoji: "🐻",
    likes: 145,
    timer: "07 : 12 : 31 : 21",
    title: "Flame Dress By Balmain...",
    blockchain: "BSC",
    author: "Tyler Covington",
    price: "4.89",
    avatar: "🔥",
    accent: "danger",
  },
];